uploads = []

[[generated]]
id = "Mbrlr1oWUS-mWgdoZZx_N"
uri = "file://artifacts/kitchen-app/assets/images/icon.png"
type = "image"
title = "prepflows icon chef hat"

[[generated]]
id = "hZ6LZ3ffuEaC1IX11ZMns"
uri = "file://artifacts/kitchen-app/assets/images/splash.png"
type = "image"
title = "prepflows splash screen"

[[outputs]]
id = "r7POdARTufhxKszBWx7G8"
uri = "file://artifacts/kitchen-app/assets/images/icon.png"
type = "image"
title = "PrepFlows App Icon"

[[outputs]]
id = "Q7qOqhWdD9Quy9e6hL8RX"
uri = "file://artifacts/kitchen-app/assets/images/splash.png"
type = "image"
title = "KitchenCommand Splash Screen"
