// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/kitchen-app/FunctionDetail.tsx": () => import("../components/mockups/kitchen-app/FunctionDetail.tsx"),
  "./components/mockups/kitchen-app/PrepList.tsx": () => import("../components/mockups/kitchen-app/PrepList.tsx"),
  "./components/mockups/kitchen-app/Roster.tsx": () => import("../components/mockups/kitchen-app/Roster.tsx"),
  "./components/mockups/kitchen-app/TodayDashboard.tsx": () => import("../components/mockups/kitchen-app/TodayDashboard.tsx")
};
