// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/kitchen-app/FunctionDetail.tsx": () => import("../components/mockups/kitchen-app/FunctionDetail.tsx"),
  "./components/mockups/kitchen-app/PrepList.tsx": () => import("../components/mockups/kitchen-app/PrepList.tsx"),
  "./components/mockups/kitchen-app/Roster.tsx": () => import("../components/mockups/kitchen-app/Roster.tsx"),
  "./components/mockups/kitchen-app/TodayDashboard.tsx": () => import("../components/mockups/kitchen-app/TodayDashboard.tsx"),
  "./components/mockups/kitchen-saas/AddFunctionFlow.tsx": () => import("../components/mockups/kitchen-saas/AddFunctionFlow.tsx"),
  "./components/mockups/kitchen-saas/AnalyticsDashboard.tsx": () => import("../components/mockups/kitchen-saas/AnalyticsDashboard.tsx"),
  "./components/mockups/kitchen-saas/FunctionPremium.tsx": () => import("../components/mockups/kitchen-saas/FunctionPremium.tsx"),
  "./components/mockups/kitchen-saas/LiveServiceMode.tsx": () => import("../components/mockups/kitchen-saas/LiveServiceMode.tsx"),
  "./components/mockups/kitchen-saas/PremiumPrepList.tsx": () => import("../components/mockups/kitchen-saas/PremiumPrepList.tsx"),
  "./components/mockups/kitchen-saas/RosterPremium.tsx": () => import("../components/mockups/kitchen-saas/RosterPremium.tsx"),
  "./components/mockups/kitchen-saas/SettingsPanel.tsx": () => import("../components/mockups/kitchen-saas/SettingsPanel.tsx"),
  "./components/mockups/kitchen-saas/TodayPremium.tsx": () => import("../components/mockups/kitchen-saas/TodayPremium.tsx")
};
